### ISSUE TITLE
OSError at

### ISSUE THREAD

**Issue by cfox4ever** [theriverman/django-minio-backend#21]
anyone have an idea about this error ? 
OSError at /APP/
stream having not enough data;expected: 1999, got: 0 bytes
Request Method: | POST

Exception Location: | /venv/lib/python3.7/site-packages/minio/api.py, line 1745, in put_object

thank yo u

**Comment by theriverman** [comment]
could you provide more information please?

- how did you implement django-minio-backend into your code?
- how are you interacting with your class/function using django-minio-backend?
- what version of django-minio-backend are you using? (hit `pip list` in your venv)
