### ISSUE TITLE
Exception ignored in: <function Minio.__del__ at 0x7f5cb166feb0>

### ISSUE THREAD

**Issue by eugenewere** [theriverman/django-minio-backend#37]
This  warning occurs when django server reloads when am using minio as a static files storage.

my static files storage setting is 

`STATICFILES_STORAGE = 'django_minio_backend.models.MinioBackendStatic'`

ERROR

`Exception ignored in: <function Minio.__del__ at 0x7f5cb166feb0>
Traceback (most recent call last):
  File "/yyy/yyyy/yyyy/yyyy/env/lib/python3.10/site-packages/minio/api.py", line 155, in __del__
  File "/yyy/yyyy/yyyy/yyyy/env/lib/python3.10/site-packages/urllib3/poolmanager.py", line 223, in clear
  File "/yyy/yyyy/yyyy/yyyy/env/lib/python3.10/site-packages/urllib3/_collections.py", line 95, in clear
TypeError: 'NoneType' object is not callable
INFO 2022-10-20 22:23:00,643 autoreload 87782 140634100062016 Watching for file changes with StatReloader`

but when using S3 [minio alternative static files settings], the error dissapears:

`STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'`

**Comment by theriverman** [comment]
Please provide more information!
What version of Django? What version of django-minio-backend? How does your class look like calling the delete method? How does delete get called on server reload at all?

**Comment by eugenewere** [comment]
Ohh... The error cleared ..it doesn't show anymore... Nothing changed... It just disappeared

Django 3.2.9
django-minio-backend==3.3.2
minio==7.1.4
