### ISSUE TITLE
ImportError: cannot import name 'utc' from 'django.utils.timezone'

### ISSUE THREAD

**Issue by DiSonDS** [theriverman/django-minio-backend#44]
[Django 5.0 release notes](https://docs.djangoproject.com/en/5.0/releases/5.0/):
> The django.utils.timezone.utc alias to datetime.timezone.utc is removed.

logs:
> ...
>    File "/usr/local/lib/python3.12/site-packages/django_minio_backend/__init__.py", line 1, in <module>
>      from .apps import *
>    File "/usr/local/lib/python3.12/site-packages/django_minio_backend/apps.py", line 3, in <module>
>      from .models import MinioBackend, MinioBackendStatic
>    File "/usr/local/lib/python3.12/site-packages/django_minio_backend/models.py", line 30, in <module>
>      from django.utils.timezone import utc
>  ImportError: cannot import name 'utc' from 'django.utils.timezone' (/usr/local/lib/python3.12/site-packages/django/utils/timezone.py)

**Comment by theriverman** [comment]
Version 3.6.0 is now pushed to PyPI
