### ISSUE TITLE
AttributeError: module 'datetime' has no attribute 'UTC'

### ISSUE THREAD

**Issue by PUD-GA** [theriverman/django-minio-backend#55]
With Django==5.1.4
and django-minio-backend==3.8.0

class PrivateAttachment(models.Model):   
    file = models.FileField(verbose_name="Object Upload",
                            storage=MinioBackend(bucket_name='test-dmb'),
                            upload_to=iso_date_prefix)

When i try to upload file from admin, i have this error :
File "/venv/lib/python3.10/site-packages/django_minio_backend/models.py", line 40, in get_iso_date
    now = datetime.datetime.now(datetime.UTC)
AttributeError: module 'datetime' has no attribute 'UTC'

**Comment by theriverman** [comment]
Update your Python version, see setup.py for more details.On 2024. Dec 29., at 18:56, PUD-GA ***@***.***> wrote:﻿
With Django==5.1.4
and django-minio-backend==3.8.0
class PrivateAttachment(models.Model):
file = models.FileField(verbose_name="Object Upload",
storage=MinioBackend(bucket_name='test-dmb'),
upload_to=iso_date_prefix)
When i try to upload file from admin, i have this error :
File "/venv/lib/python3.10/site-packages/django_minio_backend/models.py", line 40, in get_iso_date
now = datetime.datetime.now(datetime.UTC)
AttributeError: module 'datetime' has no attribute 'UTC'

**Comment by PUD-GA** [comment]
It's ok (python 3.10 --> 3.12)
Thanks a lot !
